defaults: &defaults
  app_name: "railsusefullink"
  domain: "http://railsusefullink.dev/"
  facebook_app_id: "786324161384120"
  facebook_secret: "ca4e679ecaf31bbb55085f822e548afd"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
